modLoader="javafml"
loaderVersion="[35.1,)"
credits="vincentmet"
license="All Rights Reserved"
[[mods]]
modId="customquests"
version="1.16.4-2.0.0"
displayName="Custom Quests"
description='''
Quests!!!
'''